### ISSUE TITLE
Request for a paper addition

### ISSUE THREAD

**Issue by phillipinseoul** [GuoLanqing/Awesome-High-Resolution-Diffusion#3]
Hi, thanks for the nice summary of recent works on high-resolution generation!

It would be great if you could also add our work, SyncDiffusion, to the page :)

SyncDiffusion: Coherent Montage via Synchronized Joint Diffusions (NeurIPS 2023)
- arXiv: https://arxiv.org/abs/2306.05178
- Project page: https://syncdiffusion.github.io/

Best,
Yuseung Lee

**Comment by GuoLanqing** [comment]
Have added. Thanks~

**Comment by phillipinseoul** [comment]
Thanks! Appreciate it :)
